### ISSUE TITLE
error: '_rotl' was not declared in this scope

### ISSUE THREAD

**Issue by msrbyt** [Luftschlange/ms-skim#3]
I'm working with Ubuntu and my gcc version is 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04).

I get this error upon compilation:

`./src/SKIM.h:539:7: error: '_rotl' was not declared in this scope  `
`--> "k = _rotl(k, 15);"`

The full error message is shown below:

![Screen Shot 2021-04-07 at 10 34 52 PM](https://user-images.githubusercontent.com/72044376/113959933-ad93f700-97f1-11eb-9464-df7e71e3bf37.png)

**Comment by msrbyt** [comment]
I could resolve the error by adding `#include <x86intrin.h>` to `SKIM.h` and `RSInfluenceOracle.h`
